spring:
  profiles:
    active: 
    - dev
---
spring:
  profiles:  dev
  application:
    name:  microservicecloud-config-weit-dev
---
spring:
  profiles:  test
  application:
    name:  microservicecloud-config-weit-test
        
 

